import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsBoolean,
  Allow,
  IsIn,
  IsInt,
  IsOptional,
  IsString,
  Max,
  MaxLength,
  Min,
  MinLength,
} from 'class-validator';

export const BATTLE_TIMELINE_LANGUAGES = ['vi', 'en'] as const;

export class GenerateBattleTimelineDto {
  @ApiProperty({
    description: 'Free-form battle description. Must contain enough event detail for timeline generation.',
    minLength: 30,
    maxLength: 50000,
  })
  @IsString()
  @MinLength(30)
  @MaxLength(50000)
  text!: string;

  @ApiPropertyOptional({ default: 900, minimum: 300, maximum: 2000 })
  @IsOptional()
  @IsInt()
  @Min(300)
  @Max(2000)
  mapWidth?: number;

  @ApiPropertyOptional({ default: 600, minimum: 300, maximum: 2000 })
  @IsOptional()
  @IsInt()
  @Min(300)
  @Max(2000)
  mapHeight?: number;

  @ApiPropertyOptional({ enum: BATTLE_TIMELINE_LANGUAGES, default: 'vi' })
  @IsOptional()
  @IsString()
  @IsIn(BATTLE_TIMELINE_LANGUAGES)
  language?: string;

  @ApiPropertyOptional({ default: false })
  @IsOptional()
  @IsBoolean()
  includeVoice?: boolean;
}

export class ExtractBattleDocumentDto {
  @ApiProperty({
    description: 'Raw text extracted from PDF/DOCX by the upload layer.',
    minLength: 30,
    maxLength: 120000,
  })
  @IsString()
  @MinLength(30)
  @MaxLength(120000)
  rawText!: string;

  @ApiPropertyOptional({ default: 1 })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(2000)
  pageCount?: number;
}

export class PrepareVoiceScriptDto {
  @ApiProperty({ description: 'Battle timeline JSON generated by P1.' })
  @Allow()
  timeline!: unknown;

  @ApiPropertyOptional({ enum: BATTLE_TIMELINE_LANGUAGES, default: 'vi' })
  @IsOptional()
  @IsString()
  @IsIn(BATTLE_TIMELINE_LANGUAGES)
  language?: string;
}

export class GenerateQuizDto {
  @ApiProperty({ description: 'Battle timeline JSON generated by P1.' })
  @Allow()
  timeline!: unknown;
}

export class GenerateSummaryDto {
  @ApiProperty({ description: 'Battle timeline JSON generated by P1.' })
  @Allow()
  timeline!: unknown;
}
